from fpdf import FPDF
from datetime import datetime
import os

class CRZAuditPDF(FPDF):
    def header(self):
        # Header banner
        self.set_fill_color(0, 51, 102) # Dark Blue
        self.rect(0, 0, 210, 30, 'F')
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'Coastal Regulation Zone (CRZ) Compliance Audit Report', ln=True, align='C')
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 5, 'Generated by TideVault Coastal Intelligence Platform', ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by TideVault Engine | {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

    def section_header(self, title):
        self.set_font('helvetica', 'B', 12)
        self.set_text_color(0, 51, 102)
        self.ln(5)
        self.cell(0, 10, title, border='B', ln=True)
        self.ln(2)

def generate_crz_report(data, filename="crz_report.pdf"):
    pdf = CRZAuditPDF()
    pdf.add_page()
    
    site = data.get("site", "N/A")
    analysis = data.get("site_analysis", {})
    buffers = data.get("buffer_analysis", [])
    
    # 1. SITE OVERVIEW
    pdf.section_header("SECTION 1: SITE OVERVIEW")
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(50, 8, "Site Designation:", 0, 0)
    pdf.cell(0, 8, f"{site}", 0, 1)
    pdf.cell(50, 8, "Audit Timestamp:", 0, 0)
    pdf.cell(0, 8, f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.cell(50, 8, "Spatial Reference:", 0, 0)
    pdf.cell(0, 8, "EPSG:32643 (UTM Zone 43N) / WGS84", 0, 1)
    
    # 2. COMPLIANCE SUMMARY
    pdf.section_header("SECTION 2: COMPLIANCE SUMMARY")
    status = analysis.get("compliance_status", "UNKNOWN")
    pdf.set_font('helvetica', 'B', 11)
    if status == "COMPLIANT":
        pdf.set_text_color(0, 128, 0) # Green
        pdf.cell(0, 10, f"OVERALL STATUS: {status}", 0, 1)
    else:
        pdf.set_text_color(255, 0, 0) # Red
        pdf.cell(0, 10, f"OVERALL STATUS: {status}", 0, 1)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('helvetica', '', 10)
    pdf.multi_cell(0, 6, "Analysis indicates general adherence to CRZ notification 2011 guidelines with site-specific buffer validations.", 0, 'L')
    
    # 3. VIOLATIONS DETECTED
    pdf.section_header("SECTION 3: VIOLATIONS & WARNINGS")
    notes = analysis.get("compliance_notes", [])
    if not notes:
        pdf.cell(0, 10, "No violations detected in the processed dataset.", 0, 1)
    else:
        for note in notes:
            marker = "X" if "WARNING" in note.upper() or "CRITICAL" in note.upper() else "!"
            pdf.set_font('helvetica', 'B', 10)
            pdf.cell(10, 6, f"[{marker}]", 0, 0)
            pdf.set_font('helvetica', '', 10)
            pdf.cell(0, 6, note, 0, 1)

    # 4. BUFFER / SPATIAL ANALYSIS
    pdf.section_header("SECTION 4: BUFFER / SPATIAL ANALYSIS")
    pdf.set_font('helvetica', 'B', 9)
    # Table Header
    pdf.cell(20, 8, "OID", 1, 0, 'C')
    pdf.cell(30, 8, "Class", 1, 0, 'C')
    pdf.cell(40, 8, "50m Area (sqm)", 1, 0, 'C')
    pdf.cell(40, 8, "200m Area (sqm)", 1, 0, 'C')
    pdf.cell(40, 8, "500m Area (sqm)", 1, 1, 'C')
    
    pdf.set_font('helvetica', '', 9)
    for b in buffers[:10]: # Limit to top 10 for space
        pdf.cell(20, 8, str(b["oid"]), 1, 0, 'C')
        pdf.cell(30, 8, b["crz_classification"], 1, 0, 'C')
        pdf.cell(40, 8, f"{b['buffers']['50m_area_sqm']:,.0f}", 1, 0, 'R')
        pdf.cell(40, 8, f"{b['buffers']['200m_area_sqm']:,.0f}", 1, 0, 'R')
        pdf.cell(40, 8, f"{b['buffers']['500m_area_sqm']:,.0f}", 1, 1, 'R')
    
    # 5. DATA TRACEABILITY
    pdf.section_header("SECTION 5: DATA TRACEABILITY & ISO 19115")
    pdf.set_font('helvetica', '', 10)
    pdf.cell(50, 8, "Lineage Reference:", 0, 0)
    pdf.cell(0, 8, f"ISO_19115_METADATA_{site.upper().replace(' ','_')}.xml", 0, 1)
    pdf.cell(50, 8, "Analytical Engine:", 0, 0)
    pdf.cell(0, 8, "TideVault V1.2.0-Enterprise", 0, 1)

    # 6. CERTIFICATION
    pdf.section_header("SECTION 6: CERTIFICATION")
    pdf.set_font('helvetica', 'I', 9)
    cert_text = "This report is system-generated using automated geospatial validation algorithms and aligns with ISO 19115 metadata standards. It is intended for regulatory guidance and internal audit purposes for the Maharashtra Coastal Survey framework."
    pdf.multi_cell(0, 5, cert_text)

    # Save to temp
    output_path = os.path.join("/tmp", filename) if os.name != 'nt' else os.path.join(os.environ.get('TEMP', 'C:\\temp'), filename)
    # Ensure directory exists for Windows temp
    if os.name == 'nt' and not os.path.exists(os.path.dirname(output_path)):
        os.makedirs(os.path.dirname(output_path))
        
    pdf.output(output_path)
    return output_path

if __name__ == "__main__":
    print("PDF Generator Ready.")
